[package]
name = "ren_json_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
array-init = "2.0"
indexmap = "1.9"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
