[package]
name = "parser-rust"
version = "0.1.0"
authors = ["Alpvax <alpvax@netscape.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"

[dependencies.nom]
version = "6.1"
features = ["regexp"]
