[package]
name = "lsp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ast = { path = "../ast" }
parser = { path = "../parser" }
lsp-types = "0.94.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
