[package]
name = "parser"
version = "0.1.0"
authors = ["Alpvax <alpvax@netscape.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../ast" }
lexer = { path = "../lexer" }
